# Change these first
owner: muvinai # Your GitHub organization or username, where this repository lives
repo: uptime-monitor # The name of this repository

sites:
  - name: Checkout (Front)
    url: https://www.pagar.muvinai.com/paso2/total-mensual
  - name: Checkout (Back)
    url: https://api.pagar.club/plan/total-mensual
  - name: Procesos
    url: https://procesos.apisportclub.xyz
  - name: Backend
    url: https://apisportclub.xyz/
  - name: Backoffice Buen Club
    url: https://back.buen.club/
  - name: Consulta Socio Backoffice Buen Club
    method: GET
    url: https://back.buen.club/socios
    headers:
    - "Content-Type: application/json"
    - "x-access-tokens: $BUENCLUB_TOKEN"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: MuviUptimeMonitor
  introTitle: "**MuviUptimeMonitor** is an uptime monitor and status page."
  introMessage: This is the muvinai status page which uses **real-time** data.
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
